# Read the data

data can be dowloaded from http://www.manythings.org/anki/

In [1]:
import pandas as pd
import numpy as np

In [2]:
import zipfile
import io

In [3]:
data=''
with open('../input/englishtohindi/hin.txt','rb') as readfile:
    for line in io.TextIOWrapper(readfile,'utf-8'):
        data+=line

In [4]:
#data

In [5]:
data=data.split('\n')
data[1:20]

['Help!\tबचाओ!\tCC-BY 2.0 (France) Attribution: tatoeba.org #435084 (lukaszpp) & #459377 (minshirui)',
 'Jump.\tउछलो.\tCC-BY 2.0 (France) Attribution: tatoeba.org #631038 (Shishir) & #6179121 (fastrizwaan)',
 'Jump.\tकूदो.\tCC-BY 2.0 (France) Attribution: tatoeba.org #631038 (Shishir) & #6179122 (fastrizwaan)',
 'Jump.\tछलांग.\tCC-BY 2.0 (France) Attribution: tatoeba.org #631038 (Shishir) & #6179123 (fastrizwaan)',
 'Hello!\tनमस्ते।\tCC-BY 2.0 (France) Attribution: tatoeba.org #373330 (CK) & #480306 (minshirui)',
 'Hello!\tनमस्कार।\tCC-BY 2.0 (France) Attribution: tatoeba.org #373330 (CK) & #480307 (minshirui)',
 'Cheers!\tवाह-वाह!\tCC-BY 2.0 (France) Attribution: tatoeba.org #487006 (human600) & #6179113 (fastrizwaan)',
 'Cheers!\tचियर्स!\tCC-BY 2.0 (France) Attribution: tatoeba.org #487006 (human600) & #6179114 (fastrizwaan)',
 'Got it?\tसमझे कि नहीं?\tCC-BY 2.0 (France) Attribution: tatoeba.org #455353 (FeuDRenais) & #494183 (minshirui)',
 "I'm OK.\tमैं ठीक हूँ।\tCC-BY 2.0 (France) 

In [6]:
#data[0].split('\t')

Review the data

In [7]:
len(data)

2774

# Seperate the encoder and decoder input

In [8]:
encoder_text=[]
decoder_text=[]


In [9]:
for line in data:
    try:
        in_text,out_txt,_=line.split('\t')
        encoder_text.append(in_text)
        decoder_text.append('<start>'+out_txt+'<end>')
    except:
        pass
            

In [10]:
encoder_text[1:10]

['Help!',
 'Jump.',
 'Jump.',
 'Jump.',
 'Hello!',
 'Hello!',
 'Cheers!',
 'Cheers!',
 'Got it?']

In [11]:
decoder_text[1:10]

['<start>बचाओ!<end>',
 '<start>उछलो.<end>',
 '<start>कूदो.<end>',
 '<start>छलांग.<end>',
 '<start>नमस्ते।<end>',
 '<start>नमस्कार।<end>',
 '<start>वाह-वाह!<end>',
 '<start>चियर्स!<end>',
 '<start>समझे कि नहीं?<end>']

# Build input and output sequence

In [12]:
import keras

In [13]:
from keras.preprocessing.text import Tokenizer

In [14]:
encoder_t=Tokenizer()

In [15]:
encoder_t.fit_on_texts(encoder_text)

In [16]:
encoder_seq=encoder_t.texts_to_sequences(encoder_text)

In [17]:
encoder_seq[1:10]

[[85], [544], [544], [544], [894], [894], [895], [895], [128, 10]]

In [18]:
encoder_max_lenth=max([len(txt) for txt in encoder_seq])

In [19]:
encoder_max_lenth

22

In [20]:
encoder_vocab_size=len(encoder_t.word_index)
encoder_vocab_size

2372

**Same steps for decoder also**

In [21]:
decoder_t=Tokenizer()

In [22]:
decoder_t.fit_on_texts(decoder_text)

In [23]:
#decoder_t.word_index.ix[1:10]
import itertools

#(itertools.islice( (decoder_t.word_index()),10)
#take(10, decoder_t.word_index())

In [24]:
print(decoder_t.word_index.items())

dict_items([('start', 1), ('end', 2), ('है।', 3), ('में', 4), ('नहीं', 5), ('मैं', 6), ('वह', 7), ('से', 8), ('के', 9), ('मुझे', 10), ('क्या', 11), ('है', 12), ('को', 13), ('हैं।', 14), ('की', 15), ('हो', 16), ('बहुत', 17), ('का', 18), ('उसने', 19), ('एक', 20), ('पर', 21), ('हूँ।', 22), ('था।', 23), ('तुम', 24), ('यह', 25), ('कर', 26), ('लिए', 27), ('मेरे', 28), ('कि', 29), ('और', 30), ('उसे', 31), ('हैं', 32), ('इस', 33), ('अपने', 34), ('भी', 35), ('मेरी', 36), ('मैंने', 37), ('रहा', 38), ('ने', 39), ('पास', 40), ('तो', 41), ('अपनी', 42), ('गया।', 43), ('करने', 44), ('कल', 45), ('ही', 46), ('हम', 47), ('काम', 48), ('कोई', 49), ('उसके', 50), ('तुम्हारे', 51), ('उसकी', 52), ('था', 53), ('साथ', 54), ('घर', 55), ('तुम्हें', 56), ('करना', 57), ('थी।', 58), ('उस', 59), ('मेरा', 60), ('सकते', 61), ('गया', 62), ('समय', 63), ('बात', 64), ('पता', 65), ('रही', 66), ('आप', 67), ('कुछ', 68), ('आज', 69), ('यहाँ', 70), ('तुम्हे', 71), ('उसको', 72), ('चाहिए।', 73), ('अभी', 74), ('बजे', 75), ('तक', 76

In [25]:
decoder_seq=decoder_t.texts_to_sequences(decoder_text)

In [26]:
decoder_seq[1:10]

[[1, 1440, 2],
 [1, 1441, 2],
 [1, 1442, 2],
 [1, 1443, 2],
 [1, 1444, 2],
 [1, 1445, 2],
 [1, 751, 751, 2],
 [1, 1446, 2],
 [1, 971, 29, 5, 2]]

In [27]:
decoder_max_length=max([len(text) for text in decoder_seq])

In [28]:
decoder_max_length

27

In [29]:
decoder_vocab_size=len(decoder_t.word_index)
decoder_vocab_size

2963

# Padding both the sequences

In [30]:
from keras.preprocessing.sequence import pad_sequences

In [31]:
encoder_input_data=pad_sequences(encoder_seq,maxlen=encoder_max_lenth,padding='post')
decoder_input_data=pad_sequences(decoder_seq,maxlen=decoder_max_length,padding='post')

In [32]:
encoder_input_data.shape

(2773, 22)

In [33]:
decoder_input_data.shape

(2773, 27)

In [34]:
encoder_input_data[1:10]

array([[ 85,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [544,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [544,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [544,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [894,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [894,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [895,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0],
       [895,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0, 

In [35]:
decoder_input_data[1:10]

array([[   1, 1440,    2,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   1, 1441,    2,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   1, 1442,    2,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   1, 1443,    2,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   1, 1444,    2,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [   1, 1445,    2,    0,    0,    0,    0,    0,    0,    

# Building Decoder output

In [36]:
decoder_target_data=np.zeros((decoder_input_data.shape[0],decoder_input_data.shape[1]))

In [37]:
decoder_target_data.shape

(2773, 27)

In [38]:
#shifting the data by one unit for each row , since it is a prediction of the next word
for i in range(decoder_input_data.shape[0]):
    for j in range(1,decoder_input_data.shape[1]):
        decoder_target_data[i][j-1]=decoder_input_data[i][j]
        


In [39]:
max(map(max, decoder_target_data))

# Maximum value of decoder target data

2963.0

In [40]:
decoder_target_data[:26]

array([[ 751.,    2.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [1440.,    2.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [1441.,    2.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [1442.,    2.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [1443.,    2.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
  

In [41]:
decoder_input_data.shape

(2773, 27)

In [42]:
decoder_target_data.shape

(2773, 27)

In [43]:
decoder_input_data[0]

array([  1, 751,   2,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0], dtype=int32)

In [44]:
decoder_target_data[0]

array([751.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [45]:
(decoder_vocab_size)

2963

**convert this data to one hot encoding for softmax**

In [46]:
from keras.utils import to_categorical

In [47]:
decoder_target_onehot=np.zeros((decoder_target_data.shape[0],decoder_target_data.shape[1],decoder_vocab_size+1))

In [48]:
decoder_target_onehot.shape

(2773, 27, 2964)

In [49]:
decoder_target_data.shape

(2773, 27)

In [50]:
decoder_t.word_index

{'start': 1,
 'end': 2,
 'है।': 3,
 'में': 4,
 'नहीं': 5,
 'मैं': 6,
 'वह': 7,
 'से': 8,
 'के': 9,
 'मुझे': 10,
 'क्या': 11,
 'है': 12,
 'को': 13,
 'हैं।': 14,
 'की': 15,
 'हो': 16,
 'बहुत': 17,
 'का': 18,
 'उसने': 19,
 'एक': 20,
 'पर': 21,
 'हूँ।': 22,
 'था।': 23,
 'तुम': 24,
 'यह': 25,
 'कर': 26,
 'लिए': 27,
 'मेरे': 28,
 'कि': 29,
 'और': 30,
 'उसे': 31,
 'हैं': 32,
 'इस': 33,
 'अपने': 34,
 'भी': 35,
 'मेरी': 36,
 'मैंने': 37,
 'रहा': 38,
 'ने': 39,
 'पास': 40,
 'तो': 41,
 'अपनी': 42,
 'गया।': 43,
 'करने': 44,
 'कल': 45,
 'ही': 46,
 'हम': 47,
 'काम': 48,
 'कोई': 49,
 'उसके': 50,
 'तुम्हारे': 51,
 'उसकी': 52,
 'था': 53,
 'साथ': 54,
 'घर': 55,
 'तुम्हें': 56,
 'करना': 57,
 'थी।': 58,
 'उस': 59,
 'मेरा': 60,
 'सकते': 61,
 'गया': 62,
 'समय': 63,
 'बात': 64,
 'पता': 65,
 'रही': 66,
 'आप': 67,
 'कुछ': 68,
 'आज': 69,
 'यहाँ': 70,
 'तुम्हे': 71,
 'उसको': 72,
 'चाहिए।': 73,
 'अभी': 74,
 'बजे': 75,
 'तक': 76,
 'लगता': 77,
 'किताब': 78,
 'मुझसे': 79,
 'पसंद': 80,
 'दिया।': 81,
 'थे।': 82,
 'कभी

In [51]:
for i in range(decoder_target_data.shape[0]):
    for j in range(decoder_target_data.shape[1]):
        decoder_target_onehot[i][j]=to_categorical(decoder_target_data[i][j],num_classes=decoder_vocab_size+1)

In [52]:
decoder_vocab_size-1

2962

In [53]:
decoder_target_onehot.shape

(2773, 27, 2964)

In [54]:
decoder_target_onehot[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

# Building the training Model
**We are going to use the Keras functional API this time**

In [55]:
from keras.layers import Input,Embedding,Dense,LSTM

In [56]:
# define the embeding vector length

encoder_embeding_size=50
decoder_embeding_size=50

**Build the encoder**

In [57]:
encoder_input=Input(shape=(encoder_max_lenth,))

In [58]:
encoder_embedding=Embedding(encoder_vocab_size+1,encoder_embeding_size)

In [59]:
encoder_embedding_output=encoder_embedding(encoder_input)

In [60]:
x,state_h,state_c=LSTM(256,return_state=True)(encoder_embedding_output)



**return_state =True** actually means:

the output of an LSTM is the **hidden state (h)** which is x in the above case. Now, we need the **cell state (c)** of LSTM to pass
it to the decoder. so we use return_state=True attribute

Here x and state_h are one and the same which are the hidden state of the LSTM at last time step

In [61]:
state_h.shape

TensorShape([None, 256])

In [62]:
x.shape

TensorShape([None, 256])

In [63]:
state_c.shape

TensorShape([None, 256])

In [64]:
encoder_states = [state_h, state_c]

# Build a decoder

In [65]:
decoder_input=Input(shape=(None,)) 
#( This means None * None,any number of inputs and each input any number of words)
# This is as good as Input(shape=decoder_max_lenth,)


In [66]:
decoder_embedding=Embedding(decoder_vocab_size+1,decoder_embeding_size)

In [67]:
decoder_embedding_output=decoder_embedding(decoder_input)

In [68]:
decoder_rnn=LSTM(256,return_sequences=True,return_state=True)

After the embeding layer , now we are supplying 2 inputs to LSTM layer.

1. Previous states ( which would have been set by model to some default values similart to encoder, if we do not pass it to decoder)

2. current embedding output which is the target language in the vector form

In [69]:
#Initialize initial state with encoder_states
#Output will be all hidden sequences, last 'h' state and last 'c' state

x,_,_=decoder_rnn(decoder_embedding_output,initial_state=encoder_states)

In [70]:
x.shape

TensorShape([None, None, 256])

In [71]:
decoder_dense=Dense(decoder_vocab_size+1,activation='softmax')

In [72]:
decoder_outputs=decoder_dense(x)

In [73]:
decoder_outputs.shape

TensorShape([None, None, 2964])

# Now ,the final step

# we have encoder input,decoder input, decoder output and the encoder and decoder layers

In [74]:
from keras.models import Model

**Here we are sending the decoder inputs during training. This is important point to be noted. 
It is also called Techer Forcing technique. This is to make sure that when the first prediction of the target goes wrong, we dont want to send the predicted output to the next timestep. If we send the predicted targetword to the next step, it is most likely that the entire target sequence will be wrong.
To avoid this, we send the target sequence also in the training**

In [75]:
model=Model([encoder_input,decoder_input],[decoder_outputs])

In [76]:
model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])

In [77]:
model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 22)]         0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, None)]       0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 22, 50)       118650      input_1[0][0]                    
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, None, 50)     148200      input_2[0][0]                    
_______________________________________________________________________________________

# Train the model

In [78]:
model.fit([encoder_input_data, decoder_input_data], decoder_target_onehot,
          batch_size=64,
          epochs=150)
          #validation_split=0.2)

Epoch 1/150
44/44 [==============================] - 2s 37ms/step - loss: 3.4373 - accuracy: 0.6938
Epoch 2/150
44/44 [==============================] - 2s 40ms/step - loss: 1.8930 - accuracy: 0.7129
Epoch 3/150
44/44 [==============================] - 2s 36ms/step - loss: 1.9066 - accuracy: 0.7119
Epoch 4/150
44/44 [==============================] - 2s 35ms/step - loss: 2.3332 - accuracy: 0.6764
Epoch 5/150
44/44 [==============================] - 2s 37ms/step - loss: 1.7893 - accuracy: 0.7242
Epoch 6/150
44/44 [==============================] - 2s 36ms/step - loss: 1.6766 - accuracy: 0.7438
Epoch 7/150
44/44 [==============================] - 2s 40ms/step - loss: 1.6206 - accuracy: 0.7510
Epoch 8/150
44/44 [==============================] - 2s 40ms/step - loss: 1.5804 - accuracy: 0.7534
Epoch 9/150
44/44 [==============================] - 2s 36ms/step - loss: 1.5550 - accuracy: 0.7552
Epoch 10/150
44/44 [==============================] - 2s 36ms/step - loss: 1.5345 - accuracy: 0.7568

In [79]:
model.save('seq2seq_eng_hin_training.h5')

# Building the model for prediction 

## Build the encoder model

In [80]:
encoder_model=Model(encoder_input,encoder_states)

# This means during prediction we are going to send the encoder inputs, i.e. engish text and we get the 
# states ( Cell and hidden) from the encoder

## Build the decoder model

   1. Define both the states h & C initialization
   2. Get the output from Encoder
   3. Define the decoder output
   4. Build the model
   
   





In [81]:
rnn_units=256 ## LSTM states

In [82]:
decoder_state_input_h = Input(shape=(rnn_units,)) 
# This means we are going to have 256 hidden states for each sentense becuase the rerutn_state=True for encoder 
# When we say return_state=True, it gives us the state of the LSTM for the last time step. Since we have 
#256 LSTM cells, each cell return one hidden state . 
# Hence for each sequence we will get 256 and for a batch size None*256

In [83]:
decoder_state_input_c = Input(shape=(rnn_units,))
#Same comment as above for the hidden states. Last time step for each sequence we will get the cell state

In [84]:
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
# This is a list of both that is going to be the decoder input

In [85]:
x = decoder_embedding(decoder_input) 
# We are going to use the same embedding layer of the decoder that we have trained.
# But in this case we are not going to send the input to decoder since we dont have any during prediction
# We are just going to send the 'START' word to start predicting the corresponding next work that it understood
# from training for a given combination of cell state and hidden state

In [86]:
#We will use the layer which we trained earlier i.e. decoder_rnn
rnn_outputs, state_h, state_c = decoder_rnn(x, initial_state=decoder_states_inputs)

In [87]:
#This time we are retaining the decoder states(hidden/cell) for each word
#Why do we need this?
#We need this to predict the sequence of target language words.i.e next word
decoder_states = [state_h, state_c]

In [88]:
# Last layer is Dense layer . Again we are going to use the same that we have trained before decoder_dense

decoder_outputs = decoder_dense(rnn_outputs)

## Finally, building the decoder model

In [89]:
decoder_model = Model([decoder_input] + decoder_states_inputs,  #Model inputs i.e. 'START' for the first time and the predicted word next time onwards
                     [decoder_outputs] + decoder_states)

# Predicting Output

In [90]:
# before starting the prediction we will just have the dictionary of targetword and the index
int_to_word_decoder = dict((i,c) for c, i in decoder_t.word_index.items())

In [91]:
len(int_to_word_decoder)

2963

In [92]:
int_to_word_decoder

{1: 'start',
 2: 'end',
 3: 'है।',
 4: 'में',
 5: 'नहीं',
 6: 'मैं',
 7: 'वह',
 8: 'से',
 9: 'के',
 10: 'मुझे',
 11: 'क्या',
 12: 'है',
 13: 'को',
 14: 'हैं।',
 15: 'की',
 16: 'हो',
 17: 'बहुत',
 18: 'का',
 19: 'उसने',
 20: 'एक',
 21: 'पर',
 22: 'हूँ।',
 23: 'था।',
 24: 'तुम',
 25: 'यह',
 26: 'कर',
 27: 'लिए',
 28: 'मेरे',
 29: 'कि',
 30: 'और',
 31: 'उसे',
 32: 'हैं',
 33: 'इस',
 34: 'अपने',
 35: 'भी',
 36: 'मेरी',
 37: 'मैंने',
 38: 'रहा',
 39: 'ने',
 40: 'पास',
 41: 'तो',
 42: 'अपनी',
 43: 'गया।',
 44: 'करने',
 45: 'कल',
 46: 'ही',
 47: 'हम',
 48: 'काम',
 49: 'कोई',
 50: 'उसके',
 51: 'तुम्हारे',
 52: 'उसकी',
 53: 'था',
 54: 'साथ',
 55: 'घर',
 56: 'तुम्हें',
 57: 'करना',
 58: 'थी।',
 59: 'उस',
 60: 'मेरा',
 61: 'सकते',
 62: 'गया',
 63: 'समय',
 64: 'बात',
 65: 'पता',
 66: 'रही',
 67: 'आप',
 68: 'कुछ',
 69: 'आज',
 70: 'यहाँ',
 71: 'तुम्हे',
 72: 'उसको',
 73: 'चाहिए।',
 74: 'अभी',
 75: 'बजे',
 76: 'तक',
 77: 'लगता',
 78: 'किताब',
 79: 'मुझसे',
 80: 'पसंद',
 81: 'दिया।',
 82: 'थे।',
 83: 

In [93]:
def decode_sentence(input_sequence):
    #Get the encoder state values
    decoder_initial_states_value = encoder_model.predict(input_sequence)
    
    #Build a sequence with '<start>' - starting sequence for Decoder. As mentioned earlier, we are going 
    # to send only '<Start>' to start predicting the next work for decoder 
    target_seq = np.zeros((1,1))    
    target_seq[0][0] = decoder_t.word_index['start']
    
    
    #flag to check if prediction should be stopped
    stop_loop = False
    
    
    
    #Initialize predicted sentence
    predicted_sentence = ''
   
    #start the loop
    while not stop_loop:
        
        # We are passsing the initial states as encoder output & 'Start' for the first time.
        # At the end of the loop these values will be updated both target_seq & 
        predicted_outputs, h, c = decoder_model.predict([target_seq] + 
                                                        decoder_initial_states_value)
        
       # print('shape of the predicted output',predicted_outputs.shape)
       # print(predicted_outputs)
          #Get the predicted output with highest probability
       # print( 'predicted output',predicted_outputs[0,-1])
        predicted_output = np.argmax(predicted_outputs[0,-1,:])
        
        #print(predicted_output)
        
         #Get the predicted word from predicter integer
        predicted_word = int_to_word_decoder[predicted_output]
        
        
        #Check if prediction should stop
        if(predicted_word == 'end' or len(predicted_sentence) > 27):# max_decoder_seq_length=27
            
            stop_loop = True
            continue
            
        
        
         #Updated predicted sentence. First time replace with the prediction of start
        if (len(predicted_sentence) == 0):
            predicted_sentence = predicted_word
        else:  
            # second time onwards, concatenate the current prediction with the previous prediction
            
            predicted_sentence = predicted_sentence + ' ' + predicted_word
            
        
          #Update target_seq to be the predicted word index
        target_seq[0][0] = predicted_output
        
          
            
            #Update initial states value for decoder. For the first time encoder output is used
            #next time onwards, its the decoder states
        decoder_initial_states_value = [h,c]  
    
    
    
    return predicted_sentence
            
            



# We will call the above prediction with some random text to predict the target sequence

In [94]:
#Get a random sentence
start_num = np.random.randint(0, high=len(encoder_text) - 10)
#print(start_num)

for i in range(start_num, start_num + 10):
    input_seq = encoder_input_data[i : i+1]
   # print(input_seq)
    predicted_sentence = decode_sentence(input_seq)
    print('--------')
    print ('Input sentence: ', encoder_text[i])
    print ('Predicted sentence: ', predicted_sentence )

--------
Input sentence:  Apples were on sale today.
Predicted sentence:  आज सेव सस्ते बिक रहे थे।
--------
Input sentence:  As for me, I am satisfied.
Predicted sentence:  मैं तुम्हारे साथ सफ़र करना चाहता
--------
Input sentence:  Can you come to the party?
Predicted sentence:  तुम गाड़ी चला सकते हो क्या
--------
Input sentence:  Come to my house at eight.
Predicted sentence:  मेरी माँ ने बिस्तर पर साफ़ चादर
--------
Input sentence:  Did the police arrest Tom?
Predicted sentence:  मेक्सिको में स्पैनिश बोली जाती
--------
Input sentence:  Do you believe in fairies?
Predicted sentence:  तुम परियों में विश्वास करते हो
--------
Input sentence:  Do you believe in fairies?
Predicted sentence:  तुम परियों में विश्वास करते हो
--------
Input sentence:  Do you have a larger size?
Predicted sentence:  टॉम पूछ रहा है कि तुमने उसे कॉल
--------
Input sentence:  Do you want to come along?
Predicted sentence:  तुम आज सुबह यहाँ क्यों आए
--------
Input sentence:  Don't leave the door open.
Predicted sen